services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: climate-risk-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-climate_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-climate_risk}

    ports:
      - "5432:5432"

    volumes:
      - climate_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER:-climate_user} -d ${POSTGRES_DB:-climate_risk}
      interval: 10s
      timeout: 5s
      retries: 5

  dbt:
    container_name: climate-risk-dbt

    working_dir: /usr/app

    volumes:
      - ./dbt:/usr/app
      - ./dbt/profiles:/root/.dbt

    environment:
      DBT_PROFILES_DIR: /root/.dbt
      DBT_TARGET: ${DBT_TARGET:-dev}

      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE:-TRANSFORM_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE:-CLIMATE_RISK_WH}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE:-CLIMATE_RISK}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA:-DEV}
      SNOWFLAKE_THREADS: ${SNOWFLAKE_THREADS:-4}

    entrypoint:
      - tail
      - -f
      - /dev/null

    build:
      context: .
      dockerfile: docker/dbt/Dockerfile


volumes:
  climate_postgres_data: