output "warehouse_name" {
  description = "Snowflake warehouse name."
  value       = snowflake_warehouse.main.name
}

output "database_name" {
  description = "Snowflake database name."
  value       = snowflake_database.main.name
}

output "schema_names" {
  description = "Snowflake schema names."
  value = {
    core      = snowflake_schema.core.name
    analytics = snowflake_schema.analytics.name
    audit     = snowflake_schema.audit.name
  }
}

output "core_schema_name" {
  description = "CORE schema name."
  value       = snowflake_schema.core.name
}

output "analytics_schema_name" {
  description = "ANALYTICS schema name."
  value       = snowflake_schema.analytics.name
}

output "audit_schema_name" {
  description = "AUDIT schema name."
  value       = snowflake_schema.audit.name
}

output "adls_gold_storage_integration_name" {
  description = "Snowflake Azure storage integration for canonical ADLS Gold."
  value       = snowflake_storage_integration_azure.adls_gold.name
}

output "adls_gold_azure_consent_url" {
  description = "Azure consent URL generated by Snowflake."
  value       = snowflake_storage_integration_azure.adls_gold.describe_output[0].consent_url
  sensitive   = true
}

output "adls_gold_azure_multi_tenant_app_name" {
  description = "Snowflake Azure service principal application name."
  value       = snowflake_storage_integration_azure.adls_gold.describe_output[0].multi_tenant_app_name
}

output "adls_gold_stage_name" {
  description = "External Snowflake stage for canonical ADLS Gold."
  value       = snowflake_stage_external_azure.adls_gold.fully_qualified_name
}